server:
  port: 8080

spring:
  application:
    name: SpringAI

  servlet:
    multipart:
      max-file-size: 10MB              # 允许上传较大图片
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5432/ai_db
    username: postgres
    password: xia0713
    driver-class-name: org.postgresql.Driver

  ai:
    # 向量存储配置
    vectorstore:
      pgvector:
        table-name: vector_store  # 表名,默认表名 vector_store
        dimensions: 3072          # ⚠️ 必须和你的 Embedding 模型维度一致,向量维度（不填则自动从 EmbeddingModel 获取）
        index-type: none           # 3072 维超过 pgvector HNSW/IVFFlat 的 2000 维上限，暂不建索引
        initialize-schema: true     # 【关键！】启动时自动建表建索引
        distance-type: COSINE_DISTANCE  # 距离度量，默认余弦距离
          # schema-name: public       # 默认 public
        max-document-batch-size: 10000  # 单批次最大文档数

    openai:
      # 第三方中转平台基础地址，只写到域名/端口，Spring AI 自动拼接 /v1/chat/completions
#      base-url: https://ai-gateway.ztn.cn
      base-url: https://www.micuapi.ai
      # 中转平台分配的 API 密钥，严禁写在代码中
      api-key: sk-LQKMaAjMTlyRxutKOHMC7OF0e3CoXfog46V1hxmRYq7z1xWw
#      api-key: sk-RtUONsbppcygBmXyRI56E1evZVh9sqhAwYtphlK0Jxjey2tv
      chat:
        options:
          # 中转平台对应的模型名称，和你之前 curl 用的保持一致
          model: gemini-2.0-flash-001
          # 默认温度参数，可在代码中动态覆盖。用于控制输出随机性，取值 0-1。值越低输出越稳定、确定性越强；值越高越发散、创造性越强。代码生成、信息提取类场景建议 0.1-0.3；创作类场景建议 0.7-0.9。
          temperature: 0.7
          # 默认最大输出 Token
          max-tokens: 2000
          # 默认关闭流式输出，一次性返回结果
          stream: true
          # 关键：关闭 qwen3 的思考模式，直接输出 content
          extra-body-parameters:
            enable_thinking: false

      embedding:
        options:
          model: gemini-embedding-001

#        path: /chat/completions  # 自定义接口路径.确认中转平台的接口路径是否符合 OpenAI 规范，极少数中转不带 /v1，需要额外配置
# 自定义配置（可选）
app:
  chat:
    # 系统提示词
    system-prompt: 你是一个专业的Java开发助手，回答简洁准确，多用代码示例